name: Deploy 

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          persist-credentials: false
      - name: push to branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
